### ISSUE TITLE
"bananas" would like to access the microphone.

### ISSUE THREAD

**Issue by NickBouwhuis** [mistweaverco/bananas#16] opened 2024-11-30 18:33 UTC
Over and over and over again.

![Vr22N3Ht](https://github.com/user-attachments/assets/27ec73ce-7fc0-4141-8230-256bb68c2543)

The mac app needs some work, it seems.

Also got numerous warnings about the app invading my privacy. Which is probably because the app is not signed at all?

**Comment by gorillamoe** [comment] 2024-11-30 18:42
Duplicate of #6 and will be implemented in #13

**Closed by gorillamoe** 2024-11-30 18:42 UTC
